// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace icms2_wrapper
{
    public unsafe partial class icms2_clr
    {
        public partial struct __Internal
        {
            [SuppressUnmanagedCodeSecurity]
            [DllImport("icms2_clr", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
            internal static extern global::System.IntPtr CmsOpenProfileFromFile([MarshalAs(UnmanagedType.LPStr)] string ICCProfile, [MarshalAs(UnmanagedType.LPStr)] string sAccess);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("icms2_clr", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
            internal static extern global::System.IntPtr CmsCreateTransform(global::System.IntPtr Input, uint InputFormat, global::System.IntPtr Output, uint OutputFormat, uint Intent, uint dwFlags);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("icms2_clr", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
            internal static extern int CmsCloseProfile(global::System.IntPtr hProfile);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("icms2_clr", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
            internal static extern void CmsDeleteTransform(global::System.IntPtr hTransform);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("icms2_clr", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
            internal static extern void CmsDoTransform(global::System.IntPtr Transform, global::System.IntPtr InputBuffer, global::System.IntPtr OutputBuffer, uint Size);
        }

        public static global::System.IntPtr CmsOpenProfileFromFile(string ICCProfile, string sAccess)
        {
            var __ret = __Internal.CmsOpenProfileFromFile(ICCProfile, sAccess);
            return __ret;
        }

        public static global::System.IntPtr CmsCreateTransform(global::System.IntPtr Input, uint InputFormat, global::System.IntPtr Output, uint OutputFormat, uint Intent, uint dwFlags)
        {
            var __ret = __Internal.CmsCreateTransform(Input, InputFormat, Output, OutputFormat, Intent, dwFlags);
            return __ret;
        }

        public static int CmsCloseProfile(global::System.IntPtr hProfile)
        {
            var __ret = __Internal.CmsCloseProfile(hProfile);
            return __ret;
        }

        public static void CmsDeleteTransform(global::System.IntPtr hTransform)
        {
            __Internal.CmsDeleteTransform(hTransform);
        }

        public static void CmsDoTransform(global::System.IntPtr Transform, global::System.IntPtr InputBuffer, global::System.IntPtr OutputBuffer, uint Size)
        {
            __Internal.CmsDoTransform(Transform, InputBuffer, OutputBuffer, Size);
        }
    }

    public enum Format
    {
        TYPE_XYZ_FLT = 4784156,
        TYPE_Lab_FLT = 4849692,
        TYPE_GRAY_FLT = 4390924,
        TYPE_RGB_FLT = 4456476,
        TYPE_BGR_FLT = 4457500,
        TYPE_CMYK_FLT = 4587556,
        TYPE_LabA_FLT = 4849820,
        TYPE_RGBA_FLT = 4456604,
        TYPE_ARGB_FLT = 4472988,
        TYPE_BGRA_FLT = 4474012,
        TYPE_ABGR_FLT = 4457628,
        TYPE_XYZ_DBL = 4784152,
        TYPE_Lab_DBL = 4849688,
        TYPE_GRAY_DBL = 4390920,
        TYPE_RGB_DBL = 4456472,
        TYPE_BGR_DBL = 4457496,
        TYPE_CMYK_DBL = 4587552,
        TYPE_GRAY_HALF_FLT = 4390922,
        TYPE_RGB_HALF_FLT = 4456474,
        TYPE_CMYK_HALF_FLT = 4587554,
        TYPE_RGBA_HALF_FLT = 4456602,
        TYPE_ARGB_HALF_FLT = 4472986,
        TYPE_BGR_HALF_FLT = 4457498,
        TYPE_BGRA_HALF_FLT = 4474010,
        TYPE_ABGR_HALF_FLT = 4457498,
    }

    public enum Indent
    {
        INTENT_PERCEPTUAL = 0,
        INTENT_RELATIVE_COLORIMETRIC = 1,
        INTENT_SATURATION = 2,
        INTENT_ABSOLUTE_COLORIMETRIC = 3,
        INTENT_PRESERVE_K_ONLY_PERCEPTUAL = 10,
        INTENT_PRESERVE_K_ONLY_RELATIVE_COLORIMETRIC = 11,
        INTENT_PRESERVE_K_ONLY_SATURATION = 12,
        INTENT_PRESERVE_K_PLANE_PERCEPTUAL = 13,
        INTENT_PRESERVE_K_PLANE_RELATIVE_COLORIMETRIC = 14,
        INTENT_PRESERVE_K_PLANE_SATURATION = 15
    }
}